version: '3'

services:
  database:
    image: 'postgres:latest'
    container_name: 'php_project'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: tender_db
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:


