<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230714090717 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
//        // this up() migration is auto-generated, please modify it to your needs
//        $this->addSql('DROP SEQUENCE book_id_seq CASCADE');
//        $this->addSql('CREATE SEQUENCE T001_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
//        $this->addSql('CREATE SEQUENCE ZINMM_SOF_LOT_H_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
//        $this->addSql('CREATE SEQUENCE ZTINMM_TK_H_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
//        $this->addSql('CREATE SEQUENCE ZTINMM_TK_OFR_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
//        $this->addSql('CREATE SEQUENCE ZTINMM_TK_PERS_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
//        $this->addSql('CREATE SEQUENCE ZTINMM_TK_VOTE_id_seq INCREMENT BY 1 MINVALUE 1 START 1');

        //балансовая единица
        $this->addSql('CREATE TABLE IF NOT EXISTS T001 (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    burks VARCHAR(4) NOT NULL UNIQUE,
    butxt VARCHAR(25) NOT NULL)');

        //лот
        $this->addSql('CREATE TABLE IF NOT EXISTS ZINMM_SOF_LOT_H (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    konkurs_id_id VARCHAR(12) NOT NULL,
    lot_id VARCHAR(12) NOT NULL UNIQUE,
    lot_nr VARCHAR(30) NOT NULL,
    lot_name VARCHAR(132) NOT NULL,
    ekorg VARCHAR(4) NOT NULL,
    finan_limit_wvat NUMERIC(6, 2) NOT NULL,
    finan_limit_wovat NUMERIC(6, 2) NOT NULL,
    vat_rate VARCHAR(2) NOT NULL,
    cals_nds VARCHAR(1) NOT NULL)');

//        $this->addSql('CREATE INDEX IDX_7C4A94BF5A529B16 ON ZINMM_SOF_LOT_H (konkurs_id_id)');

        //процедура
        $this->addSql('CREATE TABLE IF NOT EXISTS ZTINMM_TK_H (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    burks_id VARCHAR(4) NOT NULL,
    konkurs_id VARCHAR(12) NOT NULL UNIQUE,
    konkurs_nr VARCHAR(40) NOT NULL,
    konkurs_name VARCHAR(255) NOT NULL,
    org_key VARCHAR(3) NOT NULL,
    stat VARCHAR(5) NOT NULL,
    crt_date DATE NOT NULL,
    crt_time TIME(0) WITHOUT TIME ZONE NOT NULL,
    crt_user VARCHAR(12) NOT NULL)');
//        $this->addSql('CREATE INDEX IDX_5E92500113E7EE5 ON ZTINMM_TK_H (burks_id)');
//        $this->addSql('COMMENT ON COLUMN ZTINMM_TK_H.crt_date IS \'(DC2Type:date_immutable)\'');
//        $this->addSql('COMMENT ON COLUMN ZTINMM_TK_H.crt_time IS \'(DC2Type:time_immutable)\'');

        //предложения поставщиков
        $this->addSql('CREATE TABLE IF NOT EXISTS ZTINMM_TK_OFR (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    konkurs_id_id VARCHAR(12) NOT NULL,
    lot_id_id VARCHAR(12) NOT NULL,
    tabix NUMERIC(5, 2) NOT NULL,
    lifnr VARCHAR(10) NOT NULL UNIQUE,
    lifnr_name VARCHAR(132) NOT NULL,
    orf_date VARCHAR(20) NOT NULL,
    orf_time VARCHAR(20) WITHOUT TIME ZONE NOT NULL,
    price_nds NUMERIC(6, 2) NOT NULL,
    price_with_nds NUMERIC(6, 2) NOT NULL,
    deliver_date VARCHAR(20) NOT NULL,
    deliver_time VARCHAR(20) WITHOUT TIME ZONE NOT NULL,
    win_flg VARCHAR(1) DEFAULT NULL)');

//        $this->addSql('CREATE INDEX IDX_15A0E2065A529B16 ON ZTINMM_TK_OFR (konkurs_id_id)');
//        $this->addSql('CREATE INDEX IDX_15A0E20690CF359 ON ZTINMM_TK_OFR (lot_id_id)');
//        $this->addSql('COMMENT ON COLUMN ZTINMM_TK_OFR.orf_date IS \'(DC2Type:date_immutable)\'');
//        $this->addSql('COMMENT ON COLUMN ZTINMM_TK_OFR.orf_time IS \'(DC2Type:time_immutable)\'');
//        $this->addSql('COMMENT ON COLUMN ZTINMM_TK_OFR.deliver_date IS \'(DC2Type:date_immutable)\'');
//        $this->addSql('COMMENT ON COLUMN ZTINMM_TK_OFR.deliver_time IS \'(DC2Type:time_immutable)\'');

        //специалисты по процедуре
        $this->addSql('CREATE TABLE IF NOT EXISTS ZTINMM_TK_PERS (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    konkurs_id_id VARCHAR(12) NOT NULL,
    tabix INT NOT NULL,
    pers_func VARCHAR(5) NOT NULL,
    pers_id VARCHAR(12) NOT NULL,
    pers_fio VARCHAR(70) NOT NULL)');

//        $this->addSql('CREATE INDEX IDX_C32A13845A529B16 ON ZTINMM_TK_PERS (konkurs_id_id)');

        //бюллетень
        $this->addSql('CREATE TABLE IF NOT EXISTS ZTINMM_TK_VOTE (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    konkurs_id_id VARCHAR(12) NOT NULL,
    lifnr_id VARCHAR(10) NOT NULL,
    stat VARCHAR(5) NOT NULL,
    pers_id VARCHAR(12) NOT NULL,
    vote_res VARCHAR(1) DEFAULT NULL,
    vote_finish VARCHAR(1) DEFAULT NULL,
    vote_win VARCHAR(1) DEFAULT NULL,
    vote_date DATE DEFAULT NULL,
    vote_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL,
    vote_user VARCHAR(12) NOT NULL)');

//        $this->addSql('CREATE UNIQUE INDEX UNIQ_4958DB595A529B16 ON ZTINMM_TK_VOTE (konkurs_id_id)');
//        $this->addSql('CREATE UNIQUE INDEX UNIQ_4958DB595CD132F5 ON ZTINMM_TK_VOTE (lifnr_id)');
//        $this->addSql('COMMENT ON COLUMN ZTINMM_TK_VOTE.vote_date IS \'(DC2Type:date_immutable)\'');
//        $this->addSql('COMMENT ON COLUMN ZTINMM_TK_VOTE.vote_time IS \'(DC2Type:time_immutable)\'');

        $this->addSql('ALTER TABLE ZINMM_SOF_LOT_H ADD CONSTRAINT fk_lot_konkurs_id_id FOREIGN KEY (konkurs_id_id)
    REFERENCES ZTINMM_TK_H (konkurs_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ZTINMM_TK_H ADD CONSTRAINT fk_burks_id FOREIGN KEY (burks_id)
    REFERENCES T001 (burks) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ZTINMM_TK_OFR ADD CONSTRAINT fk_ofr_konkurs_id_id FOREIGN KEY (konkurs_id_id)
    REFERENCES ZTINMM_TK_H (konkurs_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ZTINMM_TK_OFR ADD CONSTRAINT fk_ofr_lot_id_id FOREIGN KEY (lot_id_id)
    REFERENCES ZINMM_SOF_LOT_H (lot_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ZTINMM_TK_PERS ADD CONSTRAINT fk_pers_konkurs_id_id FOREIGN KEY (konkurs_id_id)
    REFERENCES ZTINMM_TK_H (konkurs_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ZTINMM_TK_VOTE ADD CONSTRAINT fk_vote_konkurs_id_id FOREIGN KEY (konkurs_id_id)
    REFERENCES ZTINMM_TK_H (konkurs_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ZTINMM_TK_VOTE ADD CONSTRAINT fk_vote_lifnr_id FOREIGN KEY (lifnr_id)
    REFERENCES ZTINMM_TK_OFR (lifnr) ON DELETE CASCADE');

//        $this->addSql('DROP TABLE book');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
//        $this->addSql('CREATE SCHEMA public');
//        $this->addSql('DROP SEQUENCE T001_id_seq CASCADE');
//        $this->addSql('DROP SEQUENCE ZINMM_SOF_LOT_H_id_seq CASCADE');
//        $this->addSql('DROP SEQUENCE ZTINMM_TK_H_id_seq CASCADE');
//        $this->addSql('DROP SEQUENCE ZTINMM_TK_OFR_id_seq CASCADE');
//        $this->addSql('DROP SEQUENCE ZTINMM_TK_PERS_id_seq CASCADE');
//        $this->addSql('DROP SEQUENCE ZTINMM_TK_VOTE_id_seq CASCADE');
        $this->addSql('ALTER TABLE ZINMM_SOF_LOT_H DROP CONSTRAINT fk_lot_konkurs_id_id');
        $this->addSql('ALTER TABLE ZTINMM_TK_H DROP CONSTRAINT fk_burks_id');
        $this->addSql('ALTER TABLE ZTINMM_TK_OFR DROP CONSTRAINT fk_ofr_konkurs_id_id');
        $this->addSql('ALTER TABLE ZTINMM_TK_OFR DROP CONSTRAINT fk_ofr_lot_id_id');
        $this->addSql('ALTER TABLE ZTINMM_TK_PERS DROP CONSTRAINT fk_pers_konkurs_id_id');
        $this->addSql('ALTER TABLE ZTINMM_TK_VOTE DROP CONSTRAINT fk_vote_konkurs_id_id');
        $this->addSql('ALTER TABLE ZTINMM_TK_VOTE DROP CONSTRAINT fk_vote_lifnr_id');
        $this->addSql('DROP TABLE T001');
        $this->addSql('DROP TABLE ZINMM_SOF_LOT_H');
        $this->addSql('DROP TABLE ZTINMM_TK_H');
        $this->addSql('DROP TABLE ZTINMM_TK_OFR');
        $this->addSql('DROP TABLE ZTINMM_TK_PERS');
        $this->addSql('DROP TABLE ZTINMM_TK_VOTE');
    }
}
