# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
#    exceptions:
#        Symfony\Component\HttpKernel\Exception\NotFoundHttpException: { code: 404 }
#        App\Exception\MyException: { code: 404, hidden: false }
    #        App\Exception\My: { code: 409, hidden: false }
#}


services:
    # default configuration for services in *this* file
#    App\Exception\MyExceptionHandler:
#        tags: [ kernel.event_listener ]
    #        autowire: true
    #        tags:
    #            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException}


    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    #        Exception\MyExceptionHandler:
    #            autowire: true
    #            tags:
    #                - { name:
    #                      kernel.event_listener, event:
    #                      kernel.exception, method: onKernelException }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

#    App\Service\ExceptionHandler\ExceptionMappingResolver:
#        arguments: [ '%exceptions%' ]

#    App\Listener\ApiExceptionListener:
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception, priority: 10 }

    App\Exception\MyExceptionHandler:
        tags:
            - { name: kernel.event_listener, event: kernel.exception}
